root: true

parser: babel-eslint

parserOptions:
  ecmaVersion: 8
  ecmaFeatures:
    experimentalObjectRestSpread: true
  sourceType: script

extends: standard

plugins:
  - standard

env:
  browser: true
  es6: true
  webextensions: true
